### ISSUE TITLE
Question about the authn-and-authz-on-chaos-dashboard

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/rfcs#5]
> This solution need chaos-dashboard has permission about create/get/update/delete on Role/RoleBinding/Service Account/Secrets.

I don't think `chaos-dashboard` should be with these permission. The user should provide a token with these permission to login and create a user in `chaos-dashboard`.

(Though I still think create user in `chaos-dashboard` is a little awkward, I will try to persuade myself as most of you agree that we should provide this function.)

**Comment by YangKeao** [comment]
@STRRL  @WangXiangUSTC

**Comment by STRRL** [comment]
> I don't think chaos-dashboard should be with these permission. The user should provide a token with these permission to login and create a user in chaos-dashboard.

Yes, you are right. User should provide all permissions, chaos-dashboard self should not keep any privileges.

I will update this rfc soon.

**Comment by STRRL** [comment]
Conclusion: We will NOT make features like "create users on chaos-dashboard UI" so far.

More discussion will be followed with https://github.com/chaos-mesh/rfcs/issues/7 .
